/* The Project To-Do checklist seed.
 *
 * MOVED OUT OF admin.html 2026-08-14. It is large, and was downloaded on every
 * admin load even though the test list changes far less often than the
 * dashboard wrapped around it. admin.html pulls it in with a dynamic import,
 * inside runProjectTestSync, so it is fetched only when the checklist actually
 * syncs rather than on every sign-in.
 *
 * Each row is [id, area, title, steps, expected, version, status, notes,
 * retestReason]. Bump the version whenever the wording changes, or the test
 * quietly goes stale — see CLAUDE.md §0 and §9.9.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * ⭐ TRIMMED TO THE UN-AUTOMATABLE, 2026-08-25. Owner: "i need it to be as
 * simplified as possible only testing things you absolutely cannot test."
 *
 * THE RULE FOR WHETHER A ROW BELONGS HERE, AND IT IS THE ONLY RULE:
 *
 *   A row earns a place ONLY if the thing it proves happens OUTSIDE the code —
 *   a real third-party service actually doing something (EmailJS delivering,
 *   Twilio texting, PayPal moving money, Cloudinary destroying a file, Google
 *   Maps drawing a roof), real hardware (a phone, a camera, a printer), a
 *   browser permission that is per-device and cannot travel, or a judgement
 *   only a person can make by looking.
 *
 *   Everything else belongs in the automated suite. If a check CAN be written
 *   as code — a flag being set, a field being whitelisted, a total being
 *   right, a renderer producing the right words — it goes in run-all.js or one
 *   of the named test files, NOT here. Per §9.9 that happens in the same
 *   commit as the change.
 *
 * ⚠ DO NOT re-add a row here because a bug got through. A bug that got through
 *   means the automated suite was missing a check, and the fix is that check.
 *   A manual row is not a cheaper substitute for one — it is a slower one that
 *   only runs when somebody remembers.
 *
 * ⚠ WHAT WAS REMOVED, AND WHY IT IS SAFE. 125 rows became 11. The rows that
 *   went were covered by run-all.js, the Playwright specs, money-parity,
 *   season-state, build-reason, warehouse-colours, selector-contract or the
 *   option audit. Several were CONSOLIDATED rather than dropped: the fourteen
 *   Crew Portal rows became one real-phone run, the email rows became one real
 *   delivery, the three PayPal rows became one real payment, the three print
 *   rows became one stack of paper. Where a cluster was consolidated the row
 *   KEPT THE LOWEST EXISTING ID of that cluster, so the owner's score and notes
 *   survive as a Retest rather than being pruned and lost.
 *
 * ⚠ 214, 215, 216 AND 217 ARE UNTOUCHED — not even a version bump. They were
 *   added 2026-08-21 and 2026-08-25 against this exact rule (Cloudinary really
 *   destroying a file; a decision about whether enough people have replied; a
 *   list only somebody who knows the business can read; physical work with a
 *   real deadline), so the trim had nothing to say about them. Do not reword
 *   them for tidiness — a version bump costs a Retest.
 *
 * ⚠ THE FLOOR IN run-all.js MOVED WITH THIS. It was `TEST_SEED.length >= 90`,
 *   a truncation tripwire set under the old 108-row list. It is now an exact
 *   id set, because at eleven rows a count proves almost nothing and a named
 *   list fails by NAME when a row silently vanishes. Adding a row here means
 *   adding its id there, in the same commit — deliberately, the same way
 *   Suite 39 pins BULK_CHUNK_SIZE.
 *
 * ⚠ REMOVING A ROW FROM THIS SEED DELETES IT. projShouldPruneTest deletes any
 *   seeded row that leaves this file on the next login, whatever its score, so
 *   the scores and notes on the removed rows go with them. Run Health & Data →
 *   Full Backup before deploying a trim. Hand-added rows (num >= 1000) are
 *   never in the seed and are never touched.
 * ─────────────────────────────────────────────────────────────────────────
 */
export const TEST_SEED = [

  [186,"Invoices","An invoice email really arrives, and its Pay button really works","THE SUITE CANNOT DO THIS. It proves the invoice document is built right and that the correct template is chosen, but it never hands anything to EmailJS and never opens a mailbox. Only this test proves a customer actually receives their bill.\n1. Log into admin and open a test customer (Customers -> Bulk Updates -> Build Test Customer if you need one). Put YOUR OWN email address on them.\n2. Make sure they have a price on them and that they are marked completed, so there is a real bill to send.\n3. Go to the Invoices tab, find their invoice, and use the send-to-myself option so the invoice goes to your own inbox rather than to a customer.\n4. Open your email on your phone, not on the computer you sent it from.\n5. Read the whole email. Check the amount, the customer's name, and that any credit or fee shows as its own line rather than being silently folded into the total.\n6. Tap the Pay button in the email.\n7. Now mark the same test customer as having paid in full, and send again. Read that one too.","The email arrives within a minute or two, in the inbox and not in spam. The amount matches what the invoice card says. Every credit and every fee appears as its own line with words next to it, so the customer can see why the number is what it is. Tapping Pay opens the Member Portal on their own account, on a phone, without asking them to log in again. The paid version reads as a receipt and not as a demand for money. If the email never arrives at all, that is the EmailJS keys or the account, not the app - check Automation -> the keys are saved, and check the EmailJS account itself.",1,"","","New, 2026-08-25. Replaces the old rows for billing emails, the Pay button, receipts, part-payments and test sends. All of those checked wording the suite already checks; the one thing the suite cannot do is put a real email in front of a real person."],

  [111,"PayPal","Real money really moves, including a tip and a closed browser","THE SUITE CANNOT DO THIS. It proves the balance is calculated right and that the capture path writes to the correct field, but it never calls PayPal. Only this test proves a payment actually lands. USE A TEST CUSTOMER AND A SMALL AMOUNT - this is real money.\n1. Log into admin and give a test customer a small balance (a few dollars) and your own email address.\n2. Open their Member Portal the way a customer would, from their emailed link, on a phone.\n3. Pay part of the balance, and ADD A TIP.\n4. Go back to admin and open their invoice.\n5. Now do it again with the rest of the balance - but this time, the moment PayPal says it is done, CLOSE THE TAB before it returns to the portal.\n6. Wait a minute or two, then reload their invoice in admin.","After step 3, the amount paid on the invoice goes up by what you paid and NOT by the tip - the tip is tracked separately and must never be counted as money towards their bill. After step 6, the second payment is on the invoice anyway, even though the browser never came back to tell the app about it. That is the PayPal webhook doing its job, and it is the only safety net between a customer paying and the office never knowing. If the second payment is missing, the webhook is not reaching us - check it in the PayPal account before touching any code.",1,"","","New, 2026-08-25. Absorbs the separate capture, webhook and tips rows. The webhook cannot be proved any other way: it only fires when a real browser really goes away mid-payment."],

  [114,"Nightly Automation","The 7 PM run really fires, and really texts you","THE SUITE CANNOT DO THIS. It proves the billing logic, but nothing in it waits until 7 PM Mountain, and nothing in it sends a text. Only this test proves the automatic run is alive.\n1. In admin, go to Automation and check that nightly invoicing is switched ON, and that your phone number is saved as the alert number.\n2. Set up one test customer who is completed, priced, has your own email on them, and has not been billed yet.\n3. Leave it. Do not press Send Invoices Now - that is a different code path and it will hide the thing you are testing.\n4. After 7 PM Mountain that evening, check your phone.\n5. Check the email inbox for the test customer.\n6. Back in admin, look at the top of the page for the stale-run banner.","A text arrives on your phone after 7 PM saying how many were sent, skipped and errored. The test customer's invoice email is in the inbox. No red stale-run banner is showing. If the text does not arrive, the run did not fire at all - the text is sent at the END of the run, so no text means no run, and the banner should turn red within a day and a half to say so. That banner and that text are the only two things standing between a dead nightly run and a season of nobody being billed, so if either one is not working, fix that before anything else.",1,"","","New, 2026-08-25. Absorbs the summary-text and stale-banner rows. A cron firing in production on real time cannot be simulated, and neither can Twilio."],

  [67,"Crew Portal","Work one house from start to finish on a real phone","THE SUITE CANNOT DO THIS. It proves every rule the crew portal follows, and the browser specs drive it in a fake browser - but neither one is a person outdoors on a phone with one hand full. Only this test proves it is usable.\n1. On an ACTUAL PHONE, not a computer window made narrow, open the Crew Portal and log in, then pick a name from the list.\n2. Open Today's Route.\n3. Pick a house and read everything on its card without zooming - name, address, phone, gate code, outlet notes, light colours, wire colour, the house photo, and any one-time note.\n4. Tap the phone number.\n5. Tap the address.\n6. Mark the house done.\n7. On a second house, raise a Needs Fix with a note and a photo taken with the phone's camera right then.\n8. On a third, use Didn't Get To.\n9. Clock in, tick a couple of things on the daily checklist, and clock out.","Everything on the card is readable without zooming and without scrolling sideways. Tapping the phone number starts a call. Tapping the address opens maps with the right house in it. Marking done takes one tap and the house visibly leaves the list. The camera opens straight from the fix form - not a file picker asking you to find a photo you have not taken yet. Didn't Get To puts the house back to be scheduled again rather than billing anybody. If any of this is awkward with one hand in the cold, say so in the notes - that is the finding, and it will not show up in any automated check.",2,"","","Rewritten 2026-08-25. Replaces the fourteen separate Crew Portal rows. Every rule they checked is in the automated suite; what is not, and cannot be, is whether the thing works on real hardware in the field."],

  [26,"Admin","Take a photo on a real device and draw on it","THE SUITE CANNOT DO THIS. It proves the photo is stored and carried across, but it has no camera and no finger. Only this test proves the markup is usable.\n1. On a phone or tablet, log into admin and open a test customer's Edit Customer popup.\n2. Use the photo box to take a NEW picture with the device's camera, rather than choosing one already saved.\n3. Draw on the picture to highlight where the lights go, the way you would for the crew.\n4. Save, close the popup, and reopen it.\n5. Now open the same customer on a desktop computer.\n6. Do the same thing once from the quote card, before a quote has been converted, and check the drawing survives conversion.","The camera opens directly. Drawing follows your finger without lag and without the page scrolling underneath you. What you drew is still there after saving, reopening, and looking at it on a different device. The drawing made on a quote is still on the customer after they are converted. If the drawing is fine on a computer with a mouse but unusable with a finger, that is a real fail and worth writing down - the people who need to mark a photo are not sitting at a desk.",2,"","","Rewritten 2026-08-25. Absorbs the separate Add Customer, Edit Customer and quote-card photo rows. Touch drawing and a real camera are the parts no check can reach."],

  [214,"Admin","A finished fix really deletes its photo","THIS ONE DELETES A PHOTO FOR GOOD. Use a test customer and a throwaway picture.\n1. Log into admin, open a test customer and raise a fix on them with a photo attached (Notes -> the fix photo box).\n2. Right-click the photo and copy its image address, then paste it into a new browser tab. It should load.\n3. Go to \"Routes and Schedule\" (or the customer row) and mark that fix DONE.\n4. Reload the customer. The fix photo should be gone from their record.\n5. Now go back to the tab with the image address and reload it.\n6. Separately: raise a fix WITHOUT a photo on another test customer and mark it done.\n7. And on a third, raise a fix with a photo, mark it done, then UNTICK it again.","Step 5 is the whole test: the image address must now fail to load - the picture is deleted at Cloudinary, not just unlinked. Before this change the record forgot the address but the photo stayed online for ever on a public URL. Step 6 must work normally with no error and no delay. Step 7: unticking must NOT delete anything, and the photo is already gone from step 3 anyway - what matters is that unticking does not throw an error. If the photo ever fails to delete you should see a message saying so, and the picture should STILL be on the record so it can be tried again - it must never disappear from the record while staying online.",1,"","","New, 2026-08-21 (Job 4). Owner: \"we want the picture destroyed on the spot. There is no need for it after we fix the house.\" Two paths already blanked the field, which only forgets the address - the image stayed on Cloudinary on a public URL with nothing in the app pointing at it. The automated suite proves the right asset is named and that a failed delete keeps the record intact, but it never calls Cloudinary. Only this test proves the picture is actually gone."],

  [199,"Routes","Print the three papers and read them on paper","THE SUITE CANNOT DO THIS. It proves which people are on each sheet, which columns each sheet has, and that a group is one page - but it has no printer, and a sheet that is right on screen can still be unreadable in a warehouse. Only this test proves the paper works.\n1. In admin, go to the Printing tab and use Print Today.\n2. Actually print all three papers - the warehouse list and both crew lists.\n3. On the warehouse build sheet, check every page is ONE colour group, that each page counts itself and says which sheet of how many it is, and that the Bins column is filled in on every row and not just headed.\n4. Check the Why column tells you why each bundle is being built, and that an add-on says it goes into the bin they already have.\n5. On the recycle sheet, check there are two different numbers per row - the bin number to find, and how many bins.\n6. On the crew sheets, check each crew's houses are numbered from 1 and that a crew covering two towns is not blank.\n7. Hold them at arm's length under warehouse lighting.","Every page is readable at arm's length. The warehouse sheet is one pile per page, which is the whole point of it. Nothing is cut off at the right edge. Every Bins cell has a number in it - a heading with empty cells underneath is the exact failure this test exists for. On the recycle sheet the bin number to find is the number PAINTED ON THE BOX, which is not always the number on their record, and the Bins column is how many. If a crew sheet prints empty for a two-town crew, that is a real bug and has happened before.",2,"","","Rewritten 2026-08-25. Absorbs the separate crew-sheet, build-sheet and two-crew rows, and picks up the bins columns added 2026-08-25. A column check proves only the heading; a person holding the paper is the only thing that proves the cells are filled."],

  [207,"Admin","Measure Roof guesses a roofline that matches a real house","THE SUITE CANNOT DO THIS. It has no map and no eyes. Whether a guessed roofline is actually right is a judgement, and only a person looking at a house they know can make it.\n1. In admin, open a customer whose house you have actually seen.\n2. Use Measure Roof on their address.\n3. Look at where it has drawn the line.\n4. Check the line is sitting on the roof and not on the lawn, the driveway or the neighbour's house.\n5. Check only the FRONT of the house is switched on to start with.\n6. Adjust it by hand and check the footage changes as you do.\n7. Try it on an awkward one - a corner lot, a house set back a long way, or one with trees over the roof.","The guessed line lands on the actual roof of the actual house. Only the front is on until somebody turns more on, because the front is what nearly every customer is buying. The footage moves as you drag. On the awkward house it may well be wrong, and that is fine and expected - what matters is that it is obviously wrong and easy to correct by hand, rather than being subtly wrong and believable. A believable wrong number goes straight into the price, the bin count and the bundle count, because measured feet drives all three.",2,"","","Rewritten 2026-08-25. This is the clearest case in the whole checklist of a thing no code can score: the map is real, the house is real, and 'is that the roof' is a human answer."],

  [215,"Routes","Switch the season to answered-Yes-only","⚠ THIS DECIDES WHO GETS A CREW. Nothing is deleted and it can be switched straight back, but between switching and switching back the routes, the schedule and the warehouse queue all shrink. Do it once, deliberately, after the RSVP has really gone out.\n\nAUTOMATED — npm run test:season proves the mechanism: the preview counts the right people, the switch is refused before the RSVP is marked sent, and every screen that reads the season is redrawn afterwards. What is left for you is the DECISION, which no test can make: whether enough people have replied yet.\n\n1. Log into admin and click Dashboard in the menu on the left.\n2. Find the row that says \"Who the crews are sent to\". It should currently say \"Everyone except Back Next Year\".\n3. Before the RSVP has gone out, press \"Switch to answered Yes only\" and see what happens. It should refuse and tell you to mark the RSVP as sent first.\n4. Send the RSVP email for real (Automation Emails), or if it went out another way, press the button that marks the RSVP as sent by hand.\n5. Wait as long as you want to wait for replies. Days, normally.\n6. Come back to that row and press \"Check first\".\n7. Read the number and the names it gives you. That number is how many customers would come off the routes, off the schedule and out of the warehouse queue.\n8. If that number looks right, press \"Switch to answered Yes only\" and confirm.\n9. Open Routes, Schedule and the Warehouse build queue and check they have shrunk to the people who answered.\n10. Press \"Go back to everyone\" and check they all come back.","Before the RSVP is marked sent, the switch must REFUSE — with nobody asked, nobody has answered, so it would empty the season. Once it is marked sent, \"Check first\" must give you a count AND a few names before anything changes, so you are never deciding blind. After switching, Routes, Schedule and the warehouse queue must all agree — they should never show two different seasons on two tabs. Switching back must restore every single person: nothing is written to any customer, so nobody should be missing, and nobody should have lost a recycle flag or a build flag on the way.",1,"","",""],
  [216,"Admin","Read the options list and say what is missing","⚠ THIS IS THE ONE THING NO TEST CAN EVER DO, and it is not a bug hunt — it is you reading a list and knowing your own business. Every check in the system works by comparing an option we HAVE written down against the places it has to reach. An option nobody ever wrote down cannot fail anything. It is invisible on purpose, for ever, and the only way to catch it is this.\n\n1. Open docs/what-we-can-record.md in the repo, or the page version of the same list if it was sent to you.\n2. Read all fourteen. They are in two groups: the eleven a customer is asked, and the three we work out ourselves.\n3. For each one, ask: is this still a real thing we sell or ask?\n4. Then the harder question, and the reason the list exists: what do we sell, or ask people, that is NOT on this list at all?\n5. Write down anything missing, however small, and anything on the list we no longer do.","You should come out of this with either \"nothing is missing\" written down and dated, or a list of the things we sell that the software has no place for. Anything missing is not broken — it is ABSENT: nothing will complain, no test will fail, and it will simply never appear on a quote, a crew sheet or a pull list. Note that the list is generated from the code, so it cannot be out of date with what the software does; it can only be out of date with what the BUSINESS does, which is exactly what you are checking.",1,"","",""],
  [217,"Warehouse","Get the soft-light houses switched before the list is lost","⚠ THERE IS A TIME LIMIT ON THIS ONE and it is worth understanding why. Soft now counts as Warm White everywhere the software builds or groups lights, which is what you asked for. Those houses are still findable because the filter reads what is written on the record itself. BUT: if a master-sheet sync ever rewrites one of those rows, the word \"soft\" is replaced with \"Warm White\" on that record and the house drops off this list PERMANENTLY. So get the list out and written down somewhere outside the system before the next big sync.\n\n1. Log into admin and click Customers, then All Customers.\n2. Find the filter box labelled Lights.\n3. Choose \"On soft (needs switching)\".\n4. Write down every house it shows — name, customer number and address — into a document or a sheet OUTSIDE the website. There were twelve when this was last measured.\n5. Now set the Lights filter to \"No colours recorded\" and write down that list too. Those are the people nobody has asked yet.\n6. Work through the soft list: swap those houses onto real warm white when their lights are next in the warehouse.\n7. Work through the no-colours list: ring or email them and put their answer into their record.","Both filters must actually return people rather than showing an empty list — if either comes back empty, say so, because that is either very good news or a broken filter and the two look identical. The soft list is the one that can be lost: once it is written down outside the system it is safe, and until then it is not. A house on the no-colours list is one the warehouse cannot build for at all — it will be sitting in the \"Waiting on light colours\" block at the top of the build queue, so the two lists should broadly match.",1,"","",""]

];
